### ISSUE TITLE
Runtime package is not imported

### ISSUE THREAD

**Issue by cyad22** [modern-go/reflect2#14]
Runtime package used isn't imported in runtime.go file
Please fix it as fast as you can :)

**Comment by aosting** [comment]
Runtime package used isn't imported in reflect2.go

**Comment by tanelso2** [comment]
Also running into this issue

**Comment by tanelso2** [comment]
https://github.com/modern-go/reflect2/pull/15

Thanks for the PR fixing this @aosting 

Hope it gets merged soon

**Comment by mrozenblum** [comment]
Also having this issue, hoping it gets fixed asap 🙏

**Comment by tyuwan** [comment]
Also waiting for the merge.

**Comment by taowen** [comment]
sorry about that
