### ISSUE TITLE
Update mapiterinit to reflect changes in go1.18 reflect

### ISSUE THREAD

**Issue by cuonglm** [modern-go/reflect2#24]
The commit: https://github.com/golang/go/commit/1b2d794ca3ba60c2dbc958a271662784a7122739

was landed, so `reflect.mapiterinit` will change in go1.18.

See also: https://github.com/golang/go/issues/48238

**Comment by taowen** [comment]
anyone can help to maintain https://github.com/modern-go/reflect2 ? I no longer have the insight to keep up with the language evolution.
