### ISSUE TITLE
Can not use gccgo to compile .go file.

### ISSUE THREAD

**Issue by zhangckid** [modern-go/reflect2#6]
Hi All,

I found if I use any reflect2 function in my app, I can't use go build --compiler=gccgo to compile it.
It will return error like that:

go build --compiler=gccgo map_1.go 
# command-line-arguments
/tmp/go-build467403193/b023/_pkg_.a(_go_.o): In function `github_com_modern_go_reflect2.loadGo15Types':
/usr/lib/go-1.10/src/github.com/modern-go/reflect2/type_map.go:42: undefined reference to `reflect.typelinks'
/tmp/go-build467403193/b023/_pkg_.a(_go_.o): In function `github_com_modern_go_reflect2.loadGo17Types':
/usr/lib/go-1.10/src/github.com/modern-go/reflect2/type_map.go:74: undefined reference to `reflect.typelinks'
/usr/lib/go-1.10/src/github.com/modern-go/reflect2/type_map.go:78: undefined reference to `reflect.resolveTypeOff'
collect2: error: ld returned 1 exit status

Any idea to fix it?

Thanks
Zhang Chen

**Comment by hcornelis** [comment]
Hi Zhang Chen, I have ran into the same problem as you report here.
I am trying to compile Docker for powerpc 32 bit using the gccgo compiler.
Did you manage to solve this problem?
Thanks, Hugo

**Comment by advancedwebdeveloper** [comment]
Same error [here](https://github.com/modern-go/reflect2/issues/9), while building crio-o, using gollvm

CC @thanm

Ivan

**Comment by shifty21** [comment]
I got the same issue while using gccgo to compile vault.
Could it be some missing dependency of runtime library, while building the compiler gccgo? Just a guess new to gccgo world.

Shifty21
